-- DROP
DROP TABLE IF EXISTS insurance;
DROP TABLE IF EXISTS claim;
DROP TABLE IF EXISTS car_driver;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS driver;

-- DRIVER
CREATE TABLE driver
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document  VARCHAR NOT NULL,
    birthdate DATE    NOT NULL,
    PRIMARY KEY (id)
);

-- CAR
CREATE TABLE car
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model        VARCHAR NOT NULL,
    manufacturer VARCHAR NOT NULL,
    car_year     VARCHAR NOT NULL,
    fipe_value   DECIMAL NOT NULL,
    PRIMARY KEY (id)
);

-- CUSTOMER
CREATE TABLE customer
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR NOT NULL,
    driver_id INT     NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (driver_id) REFERENCES driver (id)
);

-- CAR_DRIVER
CREATE TABLE car_driver
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_id      INT NOT NULL,
    car_id         INT NOT NULL,
    is_main_driver BIT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (driver_id) REFERENCES driver (id),
    FOREIGN KEY (car_id) REFERENCES car (id)
);

-- CLAIM
CREATE TABLE claim
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    car_id     INT  NOT NULL,
    driver_id  INT  NOT NULL,
    event_date DATE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (driver_id) REFERENCES driver (id),
    FOREIGN KEY (car_id) REFERENCES car (id)
);

-- INSURANCE
CREATE TABLE insurance
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id INT       NOT NULL,
    creation_dt TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NULL,
    car_id      INT       NOT NULL,
    is_active   BIT       NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer (id),
    FOREIGN KEY (car_id) REFERENCES car (id)
);

